### ISSUE TITLE
Error with input file containing amino acid sequences

### ISSUE THREAD

**Issue by jonoave** [dekoning-lab/grand-conv#1]
grand-converg do not appear to accept input files with amino acid sequences, even with options --seqtype=aa and gencode=1 or gencode=2

Example 1
```
./gc-estimate --seqtype=aa --in=inputData/ATP2A1_paml.phy --tree=inputData/ATP2A1.tre --gencode=1 --aa-model=lg --dir=output --free-bl=1

# output
ns = 26  	ls = 957
Reading sequences, sequential format..
Reading seq # 1: Pig     
Error in sequence data file: E at 2 seq 1.
Make sure to separate the sequence from its name by 2 or more spaces.
```

Example 2
```
./gc-estimate --seqtype=aa --in=inputData/CASQ1_paml.phy --tree=inputData/CASQ1_ensembl.tre --gencode=2 --aa-model=lg --dir=output --free-bl=1

# output
388 nucleotides, not a multiple of 3!
Outputting new control file (gc-discover)...

Done gc-estimate.
```

There is no problem running the same command with a codon input file. Attached are the input files I've used (appended .txt for attachment purposes).

[ATP2A1.phy.txt](https://github.com/dekoning-lab/grand-conv/files/39997/ATP2A1.phy.txt)
[ATP2A1.tre.txt](https://github.com/dekoning-lab/grand-conv/files/39996/ATP2A1.tre.txt)
[CASQ1_ensembl.tre.txt](https://github.com/dekoning-lab/grand-conv/files/39998/CASQ1_ensembl.tre.txt)
[CASQ1_paml.phy.txt](https://github.com/dekoning-lab/grand-conv/files/39999/CASQ1_paml.phy.txt)

**Comment by nbryans** [comment]
Hi Jonoave, Using your attached files and commands I identified 2 issues:

1.  There was a bug reading the seqtype (as you suggested). I have since addressed this in commit 4fc6056. Please pull and give it a try.

2. When using interleaved phylip files (such as your attached ATP2A1.phy), an ```I``` must be included on header line. I've attached an updated ATP2A1.phy with this fix.

Please give this a try and let me know if you encounter anything else!

Thanks, Nathan

[ATP2A1_paml.phy.txt](https://github.com/dekoning-lab/grand-conv/files/40726/ATP2A1_paml.phy.txt)

**Comment by jonoave** [comment]
Hi Nathan,

Thanks for the quick reply and fix. I just tried it and it worked!

Actually there are a few more questions I have on grand-converge, which I think don't quite fit as "issues" here in github. Do you have a contact email? Or perhaps you could get in touch with me 
junhoe<at>mpi-cbg<dot>de

Thanks, Jun-Hoe

**Comment by nbryans** [comment]
Ok, I've sent you an email. Let me know if you don't receive it. Thanks.
